name: Auto Commit
on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:       # Optional: Allows manual runs

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "Automated commit at $(date)" >> contributions.txt
          git config --global user.name "YourGitHubUsername"
          git config --global user.email "youremail@example.com"
          git add .
          git commit -m "Auto-commit: $(date)"
          git push
